name: 'Veracode Upload And Scan'
description: 'Upload files to veracode and start a static scan.'
inputs:
  appname:  # id of input
    description: 'appname'
    required: true
  createprofile:  # id of input
    description: 'createprofile'
    required: true
  filepath:  # id of input
    description: 'filepath'
    required: true
  version:  # id of input
    description: 'version'
    required: true
  vid:  # id of input
    description: 'vid'
    required: true
  vkey:  # id of input
    description: 'vkey'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.appname }}
    - ${{ inputs.createprofile }}
    - ${{ inputs.filepath }}
    - ${{ inputs.version }}
    - ${{ inputs.vid }}
    - ${{ inputs.vkey }}
